version: '3'
services:
  app: 
    image: node:18.12.0-alpine
    container_name: app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - HTTP_SEVER_PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app